/**
 * SQL schema generator.
 *
 * Generates CREATE TABLE / ALTER TABLE / CREATE INDEX statements from
 * a SyncSchema. Two modes:
 *
 * - `generateCreateSQL(schema)` — full CREATE TABLE for new databases
 * - `generateAlterSQL(schema)` — ALTER TABLE ADD COLUMN for existing databases
 *
 * Both output raw Postgres-compatible SQL strings. The CLI wraps this
 * and writes to a file.
 */

import type { FieldDef, ModelDef, SyncSchema } from './schema'
import { getModelTableName, getPrimaryKey, getColumnName } from './schema'

export interface GenerateSQLOptions {
  /** HLC field name. Default: 'changed'. */
  hlcField?: string
  /** Generate ALTER TABLE (for existing tables) instead of CREATE TABLE. */
  alter?: boolean
  /** Include backfill UPDATE to set HLC on existing rows. */
  backfillHlc?: string
  /** Tombstone table name. Default: 'sync_tombstones'. */
  tombstoneTable?: string
}

/**
 * Generate SQL statements for the sync schema.
 *
 * @returns Array of SQL statements (each is a complete statement with semicolon).
 */
export function generateSQL(
  schema: SyncSchema,
  options: GenerateSQLOptions = {},
): string[] {
  const hlcField = options.hlcField ?? 'changed'
  const tombstoneTable = options.tombstoneTable ?? 'sync_tombstones'
  const alter = options.alter ?? false
  const statements: string[] = []

  for (const [modelKey, def] of Object.entries(schema)) {
    const table = getModelTableName(modelKey, def)
    const pkName = getPrimaryKey(modelKey, def)
    const pkCol = getColumnName(pkName, def)
    const hlcCol = def.fields[hlcField]
      ? getColumnName(hlcField, def)
      : hlcField

    if (alter) {
      // ALTER TABLE — add HLC column + index to existing table
      statements.push(
        `-- Add sync HLC column to existing "${table}" table`,
        `ALTER TABLE "${table}" ADD COLUMN IF NOT EXISTS "${hlcCol}" TEXT;`,
      )

      if (options.backfillHlc) {
        statements.push(
          `-- Backfill existing rows with initial HLC`,
          `UPDATE "${table}" SET "${hlcCol}" = '${options.backfillHlc}' WHERE "${hlcCol}" IS NULL;`,
        )
      }

      statements.push(
        `ALTER TABLE "${table}" ALTER COLUMN "${hlcCol}" SET NOT NULL;`,
        `CREATE INDEX IF NOT EXISTS "idx_${table}_sync" ON "${table}" ("${hlcCol}", "${pkCol}");`,
      )
    } else {
      // CREATE TABLE — full table creation
      const colDefs = buildColumnDefs(def, hlcField)
      statements.push(
        `CREATE TABLE IF NOT EXISTS "${table}" (\n  ${colDefs.join(',\n  ')}\n);`,
        `CREATE INDEX IF NOT EXISTS "idx_${table}_sync" ON "${table}" ("${hlcCol}", "${pkCol}");`,
      )
    }
  }

  // Tombstone table (always CREATE — it's sync-internal)
  statements.push(
    `-- Sync tombstone table (internal)`,
    `CREATE TABLE IF NOT EXISTS "${tombstoneTable}" (
  model TEXT NOT NULL,
  id TEXT NOT NULL,
  hlc TEXT NOT NULL,
  scope JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (model, id)
);`,
    `CREATE INDEX IF NOT EXISTS "idx_${tombstoneTable}_hlc" ON "${tombstoneTable}" (hlc);`,
  )

  return statements
}

/**
 * Format generated SQL as a single string with comments.
 */
export function formatSQL(statements: string[]): string {
  return (
    '-- Generated by better-sync\n' +
    `-- ${new Date().toISOString()}\n\n` +
    statements.join('\n\n') +
    '\n'
  )
}

// ─── Helpers ────────────────────────────────────────────────────────

function buildColumnDefs(def: ModelDef, hlcField: string): string[] {
  const cols: string[] = []
  const seenCols = new Set<string>()

  for (const [key, field] of Object.entries(def.fields)) {
    const col = field.columnName ?? key
    if (seenCols.has(col)) continue
    seenCols.add(col)

    const sqlType = fieldTypeToSQL(field)
    const constraints: string[] = []
    if (field.primaryKey) constraints.push('PRIMARY KEY')
    if (field.unique) constraints.push('UNIQUE')
    if (field.required !== false && !field.primaryKey) constraints.push('NOT NULL')

    const def_ = `"${col}" ${sqlType}${constraints.length ? ' ' + constraints.join(' ') : ''}`
    cols.push(def_)
  }

  // Add HLC column if not already in fields
  const hlcCol = def.fields[hlcField]
    ? (def.fields[hlcField]?.columnName ?? hlcField)
    : hlcField
  if (!seenCols.has(hlcCol)) {
    cols.push(`"${hlcCol}" TEXT NOT NULL`)
  }

  return cols
}

function fieldTypeToSQL(field: FieldDef): string {
  const type = field.type
  if (Array.isArray(type)) return 'TEXT' // enum → TEXT with CHECK possible later
  switch (type) {
    case 'string':
      return 'TEXT'
    case 'number':
      return 'NUMERIC'
    case 'boolean':
      return 'BOOLEAN'
    case 'date':
      return 'TIMESTAMPTZ'
    case 'json':
      return 'JSONB'
    default:
      return 'TEXT'
  }
}
