import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    client: 'src/client.ts',
    server: 'src/server.ts',
    'next-js': 'src/next-js.ts',
    node: 'src/node.ts',
    react: 'src/react.tsx',
    'adapters/drizzle': 'src/adapters/drizzle.ts',
    'adapters/memory': 'src/adapters/memory.ts',
    'adapters/pglite': 'src/adapters/pglite.ts',
    test: 'src/test.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  sourcemap: true,
  treeshake: true,
  splitting: false,
  target: 'es2022',
  outDir: 'dist',
  external: [
    'drizzle-orm',
    'pg',
    '@electric-sql/pglite',
    'better-sqlite3',
    'next',
    'hono',
    'express',
    'react',
    'ink',
  ],
})
